[package]
name = "rj_debug"
version = "0.1.0"
authors = ["penguin"]
edition = "2018"

[lib]
crate_type = [ "cdylib", "dylib", "rlib" ]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
simple-logging = "2.0.2"