#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
use super::jni::*;
use super::jni_md::*;

pub const JVMTI_VERSION_1: jint = 0x30010000;
pub const JVMTI_VERSION_1_0: jint = 0x30010000;
pub const JVMTI_VERSION_1_1: jint = 0x30010100;
pub const JVMTI_VERSION_1_2: jint = 0x30010200;

pub const JVMTI_VERSION: jint = 0x30000000 + (1 * 0x10000) + (2 * 0x100) + 1;  /* version: 1.2.1 */

//pub type jvmtiEnv = *const jvmtiInterface_1_;
pub type jthread = jobject;
pub type jthreadGroup = jobject;
pub type jlocation =jlong;
pub struct _jrawMonitorID {}
pub type jrawMonitorID = *mut _jrawMonitorID;

pub const  JVMTI_THREAD_STATE_ALIVE: jint = 0x0001;
pub const  JVMTI_THREAD_STATE_TERMINATED: jint = 0x0002;
pub const  JVMTI_THREAD_STATE_RUNNABLE: jint = 0x0004;
pub const  JVMTI_THREAD_STATE_BLOCKED_ON_MONITOR_ENTER: jint = 0x0400;
pub const  JVMTI_THREAD_STATE_WAITING: jint = 0x0080;
pub const  JVMTI_THREAD_STATE_WAITING_INDEFINITELY: jint = 0x0010;
pub const  JVMTI_THREAD_STATE_WAITING_WITH_TIMEOUT: jint = 0x0020;
pub const  JVMTI_THREAD_STATE_SLEEPING: jint = 0x0040;
pub const  JVMTI_THREAD_STATE_IN_OBJECT_WAIT: jint = 0x0100;
pub const  JVMTI_THREAD_STATE_PARKED: jint = 0x0200;
pub const  JVMTI_THREAD_STATE_SUSPENDED: jint = 0x100000;
pub const  JVMTI_THREAD_STATE_INTERRUPTED: jint = 0x200000;
pub const  JVMTI_THREAD_STATE_IN_NATIVE: jint = 0x400000;
pub const  JVMTI_THREAD_STATE_VENDOR_1: jint = 0x10000000;
pub const  JVMTI_THREAD_STATE_VENDOR_2: jint = 0x20000000;
pub const  JVMTI_THREAD_STATE_VENDOR_3: jint = 0x40000000;

pub const JVMTI_JAVA_LANG_THREAD_STATE_MASK: jint = JVMTI_THREAD_STATE_TERMINATED | JVMTI_THREAD_STATE_ALIVE | JVMTI_THREAD_STATE_RUNNABLE | JVMTI_THREAD_STATE_BLOCKED_ON_MONITOR_ENTER | JVMTI_THREAD_STATE_WAITING | JVMTI_THREAD_STATE_WAITING_INDEFINITELY | JVMTI_THREAD_STATE_WAITING_WITH_TIMEOUT;
pub const JVMTI_JAVA_LANG_THREAD_STATE_NEW: jint = 0;
pub const JVMTI_JAVA_LANG_THREAD_STATE_TERMINATED: jint = JVMTI_THREAD_STATE_TERMINATED;
pub const JVMTI_JAVA_LANG_THREAD_STATE_RUNNABLE: jint = JVMTI_THREAD_STATE_ALIVE | JVMTI_THREAD_STATE_RUNNABLE;
pub const JVMTI_JAVA_LANG_THREAD_STATE_BLOCKED: jint = JVMTI_THREAD_STATE_ALIVE | JVMTI_THREAD_STATE_BLOCKED_ON_MONITOR_ENTER;
pub const JVMTI_JAVA_LANG_THREAD_STATE_WAITING: jint = JVMTI_THREAD_STATE_ALIVE | JVMTI_THREAD_STATE_WAITING | JVMTI_THREAD_STATE_WAITING_INDEFINITELY;
pub const JVMTI_JAVA_LANG_THREAD_STATE_TIMED_WAITING: jint = JVMTI_THREAD_STATE_ALIVE | JVMTI_THREAD_STATE_WAITING | JVMTI_THREAD_STATE_WAITING_WITH_TIMEOUT;